version: 2
jobs:
  build:
    docker:
      - image: node:8.9.0

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - dependencies-

      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}

      - run: yarn lint

      - run:
          name: Building site
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn predeploy
            else
              echo "Skip building site"
            fi

      - add_ssh_keys:
          fingerprints:
            - "f2:b5:9f:ac:58:4b:e7:dd:cc:d3:15:d4:3b:d4:3b:50"

      - run:
         name: Deploying to Github
         command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
               cd dist
               git init
               git config user.name "Devseed-CI"
               git config user.email "dev@developmentseed.org"
               touch .nojekyll # Add this so GitHub doesn't try and build site
               git add .
               git commit -m "CI deploy [skip ci]"
               git remote add origin git@github.com:developmentseed/house-gerrymandering-2018.git
               git fetch
               git push origin --force --quiet HEAD:gh-pages
               rm -rf .git
             else
               echo "Skip deploying to Github"
            fi
